// Knowledge packs — curated local data for fast, accurate itineraries
// When a user picks a city with a knowledge pack, the AI gets this data
// injected into its prompt so it recommends real, specific places.

export const KNOWLEDGE_PACKS: Record<string, any> = {
  Bangkok: {
    neighborhoods: [
      {name:"Sukhumvit",vibe:"Modern, cosmopolitan, great food",best_for:["first-timers","families","couples"],stay_recommendation:"Best BTS access, malls, restaurants"},
      {name:"Old Town",vibe:"Historic, temples, riverside",best_for:["first-timers","cultural","budget"],stay_recommendation:"Grand Palace, Wat Pho walkable"},
      {name:"Chinatown (Yaowarat)",vibe:"Chaotic, neon, legendary street food",best_for:["food-focused","budget","nightlife"],stay_recommendation:"Best food street. Come 6pm when stalls open"},
      {name:"Thonglor",vibe:"Trendy, upscale, best restaurants",best_for:["nightlife","food-focused","couples"],stay_recommendation:"Where cool locals eat and drink"},
      {name:"Siam Square",vibe:"Shopping paradise, central hub",best_for:["shopping","families"],stay_recommendation:"Paragon, MBK, CentralWorld connected by skywalks"},
    ],
    places: [
      {name:"Grand Palace",category:"temple",why_go:"Former royal residence, Emerald Buddha",best_time:"arrive 8:15am",price_level:"$$",specific_dish:null,skip_if:"hate crowds",maps_url:"https://maps.google.com/?q=Grand+Palace+Bangkok"},
      {name:"Wat Pho",category:"temple",why_go:"46m reclining Buddha. Birthplace of Thai massage",best_time:"before 9am",price_level:"$",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Wat+Pho+Bangkok"},
      {name:"Chatuchak Weekend Market",category:"market",why_go:"15000+ stalls. Largest outdoor market",best_time:"Sat/Sun 9am",price_level:"$",specific_dish:null,skip_if:"not weekend",maps_url:"https://maps.google.com/?q=Chatuchak+Bangkok"},
      {name:"Jay Fai",category:"restaurant",why_go:"Michelin street food. Crab omelette legend",best_time:"arrive 2pm",price_level:"$$$",specific_dish:"Crab omelette and drunken noodles",skip_if:"on a budget",maps_url:"https://maps.google.com/?q=Jay+Fai+Bangkok"},
      {name:"Thipsamai Pad Thai",category:"restaurant",why_go:"Most famous pad thai wrapped in egg",best_time:"evening 5pm",price_level:"$",specific_dish:"Pad Thai Superb + fresh OJ",skip_if:null,maps_url:"https://maps.google.com/?q=Thipsamai+Bangkok"},
      {name:"Somtum Der",category:"restaurant",why_go:"Best som tum. Michelin Isan food",best_time:"lunch",price_level:"$",specific_dish:"Som tum with fermented fish + grilled pork neck",skip_if:"cant handle spicy",maps_url:"https://maps.google.com/?q=Somtum+Der+Bangkok"},
      {name:"Octave Rooftop Bar",category:"bar",why_go:"Three-level rooftop, 360 views, 45th floor",best_time:"5:30pm sunset",price_level:"$$$",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Octave+Rooftop+Bangkok"},
      {name:"Terminal 21 Food Court",category:"restaurant",why_go:"Cheapest good food in central Bangkok",best_time:"afternoon",price_level:"$",specific_dish:"Pad thai 35 baht",skip_if:null,maps_url:"https://maps.google.com/?q=Terminal+21+Bangkok"},
      {name:"JODD Fairs DanNeramit",category:"market",why_go:"Hottest night market. Street food, vintage",best_time:"evening 5pm weekends",price_level:"$",specific_dish:"Grilled seafood, mango sticky rice",skip_if:null,maps_url:"https://maps.google.com/?q=JODD+Fairs+Bangkok"},
    ],
    tips: [
      {importance:"critical",tip:"Download Grab - its the Uber of SE Asia. Local taxis overcharge."},
      {importance:"critical",tip:"If anyone says Grand Palace is closed - scam. Walk past."},
      {importance:"important",tip:"Cover knees and shoulders at temples."},
      {importance:"important",tip:"BTS/MRT fastest. Traffic brutal. Get Rabbit card."},
      {importance:"important",tip:"Rooftop bars enforce dress codes. No shorts/sandals."},
      {importance:"useful",tip:"Temples before 10am. Aircon malls 12-3pm."},
    ],
  },
  Tokyo: {
    neighborhoods: [
      {name:"Shinjuku",vibe:"Neon chaos, best nightlife",best_for:["first-timers","nightlife","solo"],stay_recommendation:"Most connected station. Kabukicho nightlife"},
      {name:"Shibuya",vibe:"Young, trendy, iconic crossing",best_for:["first-timers","couples","nightlife"],stay_recommendation:"Shibuya Crossing. Backstreet restaurants"},
      {name:"Asakusa",vibe:"Old Tokyo, Senso-ji, traditional",best_for:["cultural","budget","family"],stay_recommendation:"Temple atmosphere. Cheaper. Skytree walkable"},
      {name:"Ginza",vibe:"Upscale shopping, fine dining",best_for:["luxury","couples","shopping"],stay_recommendation:"Department stores, Michelin restaurants"},
      {name:"Harajuku",vibe:"Fashion, quirky culture, cafes",best_for:["shopping","friends","art"],stay_recommendation:"Takeshita for chaos, Omotesando for designer"},
      {name:"Akihabara",vibe:"Anime, electronics, gaming",best_for:["friends","solo","family"],stay_recommendation:"Manga shops, maid cafes, retro arcades"},
    ],
    places: [
      {name:"Senso-ji Temple",category:"temple",why_go:"Tokyos oldest. Nakamise street iconic",best_time:"7am empty or evening lanterns",price_level:"free",specific_dish:null,skip_if:"only 1 day",maps_url:"https://maps.google.com/?q=Senso-ji+Tokyo"},
      {name:"Meiji Shrine",category:"temple",why_go:"Forest shrine in Harajuku",best_time:"morning before 10am",price_level:"free",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Meiji+Shrine+Tokyo"},
      {name:"Shibuya Crossing",category:"landmark",why_go:"Worlds busiest intersection",best_time:"evening rush or rainy nights",price_level:"free",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Shibuya+Crossing+Tokyo"},
      {name:"Shibuya Sky",category:"observation",why_go:"Best deck. 360 outdoor rooftop",best_time:"sunset, book 2 weeks ahead",price_level:"$$",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Shibuya+Sky+Tokyo"},
      {name:"teamLab Borderless",category:"museum",why_go:"Immersive digital art. Book 2+ weeks ahead",best_time:"weekday pre-booked",price_level:"$$",specific_dish:null,skip_if:"sold out",maps_url:"https://maps.google.com/?q=teamLab+Borderless+Tokyo"},
      {name:"Tsukiji Outer Market",category:"market",why_go:"#1 food spot. Sushi breakfast, tamagoyaki",best_time:"7am, close by 2pm",price_level:"$$",specific_dish:"Tamagoyaki stick + uni sushi",skip_if:null,maps_url:"https://maps.google.com/?q=Tsukiji+Outer+Market+Tokyo"},
      {name:"Ichiran Ramen",category:"restaurant",why_go:"Solo booth ramen. Customize on form",best_time:"late night",price_level:"$",specific_dish:"Tonkotsu, extra rich, firm noodles, extra chashu",skip_if:null,maps_url:"https://maps.google.com/?q=Ichiran+Ramen+Shibuya+Tokyo"},
      {name:"Fuunji",category:"restaurant",why_go:"Best tsukemen in Tokyo",best_time:"lunch 11am",price_level:"$",specific_dish:"Tsukemen large",skip_if:null,maps_url:"https://maps.google.com/?q=Fuunji+Shinjuku+Tokyo"},
      {name:"Omoide Yokocho",category:"restaurant",why_go:"Yakitori under train tracks. Old Tokyo",best_time:"evening 6pm",price_level:"$",specific_dish:"Yakitori - skin, heart, thigh",skip_if:"claustrophobic",maps_url:"https://maps.google.com/?q=Omoide+Yokocho+Tokyo"},
      {name:"Golden Gai",category:"bar",why_go:"200+ tiny bars in 6 alleys",best_time:"after 8pm",price_level:"$$",specific_dish:null,skip_if:"dont drink",maps_url:"https://maps.google.com/?q=Golden+Gai+Tokyo"},
      {name:"Hakone Day Trip",category:"daytrip",why_go:"Mt Fuji views, hot springs, 90min from Shinjuku",best_time:"clear day. Hakone Freepass",price_level:"$$",specific_dish:"Black eggs at Owakudani",skip_if:"cloudy",maps_url:"https://maps.google.com/?q=Hakone+Japan"},
    ],
    tips: [
      {importance:"critical",tip:"Get Suica/Pasmo IC card. Tap trains, buses, convenience stores."},
      {importance:"critical",tip:"7-Eleven ATMs only reliable for foreign cards. Cash needed many places."},
      {importance:"important",tip:"No tipping. Ever. Considered rude."},
      {importance:"important",tip:"Trains stop midnight. Miss it = expensive taxi."},
      {importance:"important",tip:"Shoes off indoors - temples, restaurants, fitting rooms."},
      {importance:"critical",tip:"Book teamLab 2+ weeks ahead. No walk-ins."},
      {importance:"useful",tip:"Depachika discount bento after 5pm - 30-50% off."},
      {importance:"useful",tip:"7-Eleven onigiri and egg sandwiches are amazing cheap food."},
    ],
  },
  Paris: {
    neighborhoods: [
      {name:"Le Marais (3rd/4th)",vibe:"Trendy, historic, best food",best_for:["first-timers","couples","food","art"],stay_recommendation:"Best overall. Walkable. Falafel, galleries, vintage"},
      {name:"Saint-Germain (6th)",vibe:"Literary, elegant, cafe culture",best_for:["couples","cultural","luxury"],stay_recommendation:"Classic Paris. Cafe de Flore. Romantic"},
      {name:"Montmartre (18th)",vibe:"Bohemian hilltop, Sacre-Coeur",best_for:["cultural","budget","couples"],stay_recommendation:"Charming but hilly. Watch for pickpockets"},
      {name:"Latin Quarter (5th)",vibe:"Student area, cheap eats",best_for:["budget","solo","friends"],stay_recommendation:"Rue Mouffetard restaurants. Near Luxembourg Gardens"},
      {name:"Bastille (11th)",vibe:"Local nightlife, natural wine",best_for:["nightlife","food","friends"],stay_recommendation:"Where young Parisians go out"},
      {name:"Canal Saint-Martin (10th)",vibe:"Hip, brunch, footbridges",best_for:["solo","couples","food"],stay_recommendation:"Sunday brunch scene, canal picnics"},
    ],
    places: [
      {name:"Eiffel Tower",category:"landmark",why_go:"Book summit online weeks ahead",best_time:"sunset summit. Sparkles every hour at night",price_level:"$$",specific_dish:null,skip_if:"hate queues",maps_url:"https://maps.google.com/?q=Eiffel+Tower+Paris"},
      {name:"Louvre",category:"museum",why_go:"Winged Victory is the real star, not Mona Lisa",best_time:"Wed/Fri evening until 9:45pm",price_level:"$$",specific_dish:null,skip_if:"only going for Mona Lisa",maps_url:"https://maps.google.com/?q=Louvre+Paris"},
      {name:"Sacre-Coeur",category:"landmark",why_go:"Best free panoramic view of Paris",best_time:"sunrise empty, sunset golden",price_level:"free",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Sacre+Coeur+Paris"},
      {name:"Notre-Dame",category:"landmark",why_go:"Reopened 2024 after fire. Free, book slot",best_time:"morning weekday",price_level:"free",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Notre+Dame+Paris"},
      {name:"Du Pain et des Idees",category:"bakery",why_go:"Best bakery in Paris",best_time:"before 11am, CLOSED weekends",price_level:"$",specific_dish:"Escargot pistache-chocolat pastry",skip_if:"weekend",maps_url:"https://maps.google.com/?q=Du+Pain+et+des+Idees+Paris"},
      {name:"LAs du Fallafel",category:"restaurant",why_go:"Best falafel in Europe",best_time:"lunch, avoid Fri/Sat Shabbat",price_level:"$",specific_dish:"Falafel special with everything",skip_if:"Shabbat",maps_url:"https://maps.google.com/?q=LAs+du+Fallafel+Paris"},
      {name:"Bouillon Chartier",category:"restaurant",why_go:"1896 Belle Epoque canteen. 3 courses 20 euros",best_time:"arrive 11:30am or 6pm",price_level:"$",specific_dish:"Oeuf mayo, steak frites, profiteroles",skip_if:null,maps_url:"https://maps.google.com/?q=Bouillon+Chartier+Paris"},
      {name:"Cafe de Flore",category:"cafe",why_go:"Sartre and Hemingway drank here",best_time:"morning terrace",price_level:"$$$",specific_dish:"Chocolat chaud - thick and legendary",skip_if:"on a budget",maps_url:"https://maps.google.com/?q=Cafe+de+Flore+Paris"},
      {name:"Pink Mamma",category:"restaurant",why_go:"5-story Italian, rooftop. No reservations",best_time:"arrive 6pm",price_level:"$$",specific_dish:"Truffle pizza + burrata, 5th floor",skip_if:"hate waiting",maps_url:"https://maps.google.com/?q=Pink+Mamma+Paris"},
      {name:"Le Syndicat",category:"bar",why_go:"Best cocktail bar. French spirits only",best_time:"evening 7pm",price_level:"$$",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Le+Syndicat+Paris"},
      {name:"Shakespeare and Company",category:"bookshop",why_go:"Worlds most famous English bookshop",best_time:"opening or evening readings",price_level:"free",specific_dish:null,skip_if:null,maps_url:"https://maps.google.com/?q=Shakespeare+and+Company+Paris"},
    ],
    tips: [
      {importance:"critical",tip:"Pickpockets at Eiffel Tower, Sacre-Coeur, Metro. Cross-body bag."},
      {importance:"critical",tip:"Download Citymapper. Way better than Google Maps for Paris."},
      {importance:"important",tip:"Say Bonjour entering ANY shop/restaurant. Bonsoir after 6pm."},
      {importance:"useful",tip:"Lunch prix fixe - Michelin spots 25-40 euros. Dinner = double."},
      {importance:"important",tip:"Louvre closed Tue, Orsay closed Mon. Check before going."},
      {importance:"important",tip:"Free water: une carafe deau. Dont pay for Evian."},
      {importance:"critical",tip:"RER B from airport: scammers help at machines then demand money."},
    ],
  },
};
